name: push to lougao acr

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: registry.us-east-1.aliyuncs.com
          username: ${{ secrets.LOUGAO_ACR_USER }}
          password: ${{ secrets.LOUGAO_ACR_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: registry.us-east-1.aliyuncs.com/lougaocloud/serverless-wp:${{ steps.get_version.outputs.VERSION }}
